openapi: 3.0.3
info:
  description: "This is server for Employee-Management system."
  version: "1.0.11"
  title: "Employee-Management system"
servers:
  - url: http://localhost:8080
tags:
  - name: employee
    description: Everything about employee
paths:
  /api/add-employee:
    post:
      tags:
        - employee
      summary: "Create New employee"
      description: "Create New employee"
      operationId: "CreateEmployee"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
          application/xml:
            schema:
              $ref: '#/components/schemas/Employee'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '405':
          description: Invalid input
  
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int
          example: 10
        name:
          type: string
          example: theUser
        position:
          type: string
          example: Engineer
        Salary:
          type: float64
          example: 950000
        created_at:
          type: string
          format: date-time
          example: 2022-08-14T19:33:16.428870284+05:30
        updated_at:
          type: string
          format: date-time
          example: 2022-08-14T19:33:16.428870284+05:30
      xml:
        name: user

   